///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModel {
/*
{
  "CODUSER": "002",
  "CODIGO": "000007",
  "NOME": "VANIA ROSARIO",
  "LOGIN": "VANIA",
  "SENHA": "0309",
  "CODVENDED": "00000006",
  "CODEMPRESA": 1
} 
*/

  String? CODUSER;
  String? CODIGO;
  String? NOME;
  String? LOGIN;
  String? SENHA;
  String? CODVENDED;
  int? CODEMPRESA;

  LoginModel({
    this.CODUSER,
    this.CODIGO,
    this.NOME,
    this.LOGIN,
    this.SENHA,
    this.CODVENDED,
    this.CODEMPRESA,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    CODUSER = json['CODUSER']?.toString();
    CODIGO = json['CODIGO']?.toString();
    NOME = json['NOME']?.toString();
    LOGIN = json['LOGIN']?.toString();
    SENHA = json['SENHA']?.toString();
    CODVENDED = json['CODVENDED']?.toString();
    CODEMPRESA = json['CODEMPRESA']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['CODUSER'] = CODUSER;
    data['CODIGO'] = CODIGO;
    data['NOME'] = NOME;
    data['LOGIN'] = LOGIN;
    data['SENHA'] = SENHA;
    data['CODVENDED'] = CODVENDED;
    data['CODEMPRESA'] = CODEMPRESA;
    return data;
  }
}
