name: jmobileflutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  another_flushbar: ^1.12.29
  auto_size_text: ^3.0.0
  cryptography: ^2.5.0
  encrypt: ^5.0.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  hive: ^2.2.3
  http: ^1.2.2
  intl: ^0.18.0
  lottie: ^3.1.2
  open_file: ^3.5.3
  # package_info: ^2.0.2
  path_provider: ^2.0.14
  provider: ^6.0.5
  responsive_sizer: ^3.2.0
  html: ^0.15.5
  syncfusion_flutter_charts: ^27.2.3
  geolocator: ^13.0.2
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.5.1
  archive: ^3.3.7
  bluetooth_thermal_printer_plus: ^0.0.2
  esc_pos_utils: ^1.1.0
  flutter_blue_plus: ^1.32.1

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  
  
  assets:
    - lib/app/common/assets/
    - lib/app/common/assets/lottie/
    - lib/app/common/assets/png/
    - lib/app/common/assets/svg/
